call cd client-examples/node-wot/phymotion-controllers-app
call git status
call cd ..
call cd spectrometer-smartphone
call git status
call cd ..
call cd ..
call cd oceanoptics-spectrometer-desktop-app 
call git status
call cd ..
call cd ..
call cd server-examples/oceanoptics-spectrometer
call git status
call cd .. 
call cd phymotion-controllers
call git status 
call cd ..
call cd serial-utility
call git status
call cd ..
call cd ..